-- Admin provisioning must use Supabase Auth with a private password.
-- Never store passwords or auth.users inserts in a public migration.
-- The existing college teacher account remains in Supabase.
